name: ascendfcu
adopt-info: ascendfcu
summary: An Electron app for AscendFCU
description: |
  An unofficial Electron application to manage your online banking with Ascend Federal Credit Union

license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  ascendfcu:
    command: bin/AscendFCU-linux-x64/AscendFCU
    extensions:
      - gnome-3-38
    plugs:
      - home
      - network
      
parts:
  ascendfcu:
    source:
    source-type: git
    plugin: nil
    build-snaps:
      - nativefier
    
    override-build: |
      nativefier --name AscendFCU --tray --single-instance --block-external-urls --clear-cache false https://ascend.org/
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -r AscendFCU-linux-x64/ $SNAPCRAFT_PART_INSTALL/bin
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"                
