name: ascendfcu
#adopt-info: ascendfcu
version: '1.0'
summary: An Electron app for AscendFCU
description: |
  An unofficial Electron application to manage your online banking with Ascend Federal Credit Union

license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  ascendfcu: https://github.com/kz6fittycent/ascendfcu
    command: bin/AscendFCU-linux-x64/AscendFCU
    extensions:
      - gnome-3-38
    plugs:
      - home
      - network
      
parts:
  ascendfcu:
    source:
    source-type: git
    plugin: nil
    build-snaps:
      - nativefier
    
    override-build: |
      mkdir -p $BUILD
      cd $BUILD
      nativefier --name AscendFCU --tray --single-instance --block-external-urls --clear-cache false https://ascend.org/
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -r AscendFCU-linux-x64/ $SNAPCRAFT_PART_INSTALL/bin
